# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160424_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
