# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160425_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
